font_family FiraCode Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto

font_size 11.5

window_padding_width 18

# Make ctrl+tab and crtl+shift+tab work, for mapping in nvim
map  ctrl+tab        send_text normal,application \x1b[9;5u
map  ctrl+shift+tab  send_text normal,application \x1b[9;6u

confirm_os_window_close 0




# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME