# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=desc:Philips Consumer Electronics Company PHL 346P1C AU02039008979,3440x1440@60,-3440x0,1
monitor=desc:Japan Display Inc. 0x422A,preferred,0x0,1.6
monitor=,preferred,auto,auto

