# Environment variables

#env = AQ_DRM_DEVICES,/dev/dri/card1 # select GPUs to use
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
# I required this to fix the issue where the laptop display would freeze when the external
# monitor was plugged in. Got the fix from this FAQ:
# https://wiki.hypr.land/FAQ/#my-external-monitor-is-blank--doesnt-render--receives-no-signal-laptop
env = AQ_NO_MODIFIERS,1

exec = ~/.config/hypr/matebook-lid.sh

# Lid switch
# trigger when the switch is turning on
bindl=,switch:on:Lid Switch,exec,~/.config/hypr/matebook-lid.sh closed
# trigger when the switch is turning off
bindl=,switch:off:Lid Switch,exec,~/.config/hypr/matebook-lid.sh open
